version: "3"

services:
  db:
    image: postgres:latest
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "3334:5432"
  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 --binding=0.0.0.0"
    volumes:
      - bundle:/app/vendor/bundle
      - node_modules:/app/node_modules
      - tmp:/app/tmp
      - .:/app:delegated
    ports:
      - "3333:3000"
    depends_on:
      - db
    environment:
      TZ: "Asia/Tokyo"
    stdin_open: true
    tty: true

volumes:
  bundle:
  node_modules:
  tmp:
