# frozen_string_literal: true

dividend_aristocrats = [
  { symbol: "ABBV", name: "AbbVie Inc.", exchange: "New York Stock Exchange", industry: "Drug Manufacturers—General", sector: "Healthcare", country: "US",
    currency: "USD", exchange_short_name: "NYSE", ipo_date: "2013-01-02", image: "https://financialmodelingprep.com/image-stock/ABBV.png", years_of_dividend_growth: 49 },
  { symbol: "ABT", name: "Abbott Laboratories", exchange: "New York Stock Exchange", industry: "Medical Devices", sector: "Healthcare", country: "US",
    currency: "USD", exchange_short_name: "NYSE", ipo_date: "1937-03-01", image: "https://financialmodelingprep.com/image-stock/ABT.png", years_of_dividend_growth: 49 },
  { symbol: "ADM", name: "Archer-Daniels-Midland Company", exchange: "New York Stock Exchange", industry: "Farm Products", sector: "Consumer Defensive",
    country: "US", currency: "USD", exchange_short_name: "NYSE", ipo_date: "1924-12-24", image: "https://financialmodelingprep.com/image-stock/ADM.png", years_of_dividend_growth: 47 },
  { symbol: "ADP", name: "Automatic Data Processing, Inc.", exchange: "Nasdaq Global Select", industry: "Staffing & Employment Services",
    sector: "Industrials", country: "US", currency: "USD", exchange_short_name: "NASDAQ", ipo_date: "1961-09-01", image: "https://financialmodelingprep.com/image-stock/ADP.png", years_of_dividend_growth: 46 },
  { symbol: "AFL", name: "Aflac Incorporated", exchange: "New York Stock Exchange", industry: "Insurance—Life", sector: "Financial Services", country: "US",
    currency: "USD", exchange_short_name: "NYSE", ipo_date: "1974-06-15", image: "https://financialmodelingprep.com/image-stock/AFL.png", years_of_dividend_growth: 38 },
  { symbol: "ALB", name: "Albemarle Corporation", exchange: "New York Stock Exchange", industry: "Specialty Chemicals", sector: "Basic Materials",
    country: "US", currency: "USD", exchange_short_name: "NYSE", ipo_date: "1994-02-22", image: "https://financialmodelingprep.com/image-stock/ALB.png", years_of_dividend_growth: 27 },
  { symbol: "AMCR", name: "Amcor plc", exchange: "New York Stock Exchange", industry: "Packaging & Containers", sector: "Consumer Cyclical", country: "GB",
    currency: "USD", exchange_short_name: "NYSE", ipo_date: "2019-06-11", image: "https://financialmodelingprep.com/image-stock/AMCR.png", years_of_dividend_growth: 38 },
  { symbol: "AOS", name: "A. O. Smith Corporation", exchange: "New York Stock Exchange", industry: "Specialty Industrial Machinery", sector: "Industrials",
    country: "US", currency: "USD", exchange_short_name: "NYSE", ipo_date: "1994-12-14", image: "https://financialmodelingprep.com/image-stock/AOS.png", years_of_dividend_growth: 28 },
  { symbol: "APD", name: "Air Products and Chemicals, Inc.", exchange: "New York Stock Exchange", industry: "Chemicals", sector: "Basic Materials",
    country: "US", currency: "USD", exchange_short_name: "NYSE", ipo_date: "1961-11-13", image: "https://financialmodelingprep.com/image-stock/APD.png", years_of_dividend_growth: 39 },
  { symbol: "ATO", name: "Atmos Energy Corporation", exchange: "New York Stock Exchange", industry: "Utilities—Regulated Gas", sector: "Utilities",
    country: "US", currency: "USD", exchange_short_name: "NYSE", ipo_date: "1988-10-03", image: "https://financialmodelingprep.com/image-stock/ATO.png", years_of_dividend_growth: 34 },
  { symbol: "BDX", name: "Becton, Dickinson and Company", exchange: "New York Stock Exchange", industry: "Medical Instruments & Supplies",
    sector: "Healthcare", country: "US", currency: "USD", exchange_short_name: "NYSE", ipo_date: "1963-09-25", image: "https://financialmodelingprep.com/image-stock/BDX.png", years_of_dividend_growth: 49 },
  { symbol: "BEN", name: "Franklin Resources, Inc.", exchange: "New York Stock Exchange", industry: "Asset Management", sector: "Financial Services",
    country: "US", currency: "USD", exchange_short_name: "NYSE", ipo_date: "1986-12-05", image: "https://financialmodelingprep.com/image-stock/BEN.png", years_of_dividend_growth: 40 },
  { symbol: "BF-B", name: "Brown-Forman Corporation", exchange: "New York Stock Exchange", industry: "Beverages—Wineries & Distilleries",
    sector: "Consumer Defensive", country: "US", currency: "USD", exchange_short_name: "NYSE", ipo_date: "1991-05-09", image: "https://financialmodelingprep.com/image-stock/BF-B.jpg", years_of_dividend_growth: 37 },
  { symbol: "CAH", name: "Cardinal Health, Inc.", exchange: "New York Stock Exchange", industry: "Medical Distribution", sector: "Healthcare", country: "US",
    currency: "USD", exchange_short_name: "NYSE", ipo_date: "1994-09-07", image: "https://financialmodelingprep.com/image-stock/CAH.png", years_of_dividend_growth: 34 },
  { symbol: "CAT", name: "Caterpillar Inc.", exchange: "New York Stock Exchange", industry: "Farm & Heavy Construction Machinery", sector: "Industrials",
    country: "US", currency: "USD", exchange_short_name: "NYSE", ipo_date: "1929-12-02", image: "https://financialmodelingprep.com/image-stock/CAT.png", years_of_dividend_growth: 27 },
  { symbol: "CB", name: "Chubb Limited", exchange: "New York Stock Exchange", industry: "Insurance—Property & Casualty", sector: "Financial Services",
    country: "CH", currency: "USD", exchange_short_name: "NYSE", ipo_date: "2008-07-18", image: "https://financialmodelingprep.com/image-stock/CB.png", years_of_dividend_growth: 28 },
  { symbol: "CINF", name: "Cincinnati Financial Corporation", exchange: "Nasdaq Global Select", industry: "Insurance—Property & Casualty",
    sector: "Financial Services", country: "US", currency: "USD", exchange_short_name: "NASDAQ", ipo_date: "1980-03-17", image: "https://financialmodelingprep.com/image-stock/CINF.png", years_of_dividend_growth: 61 },
  { symbol: "CL", name: "Colgate-Palmolive Company", exchange: "New York Stock Exchange", industry: "Household & Personal Products",
    sector: "Consumer Defensive", country: "US", currency: "USD", exchange_short_name: "NYSE", ipo_date: "1930-03-31", image: "https://financialmodelingprep.com/image-stock/CL.png", years_of_dividend_growth: 59 },
  { symbol: "CLX", name: "The Clorox Company", exchange: "New York Stock Exchange", industry: "Household & Personal Products", sector: "Consumer Defensive",
    country: "US", currency: "USD", exchange_short_name: "NYSE", ipo_date: "1968-08-01", image: "https://financialmodelingprep.com/image-stock/CLX.png", years_of_dividend_growth: 45 },
  { symbol: "CTAS", name: "Cintas Corporation", exchange: "Nasdaq Global Select", industry: "Specialty Business Services", sector: "Industrials",
    country: "US", currency: "USD", exchange_short_name: "NASDAQ", ipo_date: "1983-01-01", image: "https://financialmodelingprep.com/image-stock/CTAS.png", years_of_dividend_growth: 37 },
  { symbol: "CVX", name: "Chevron Corporation", exchange: "New York Stock Exchange", industry: "Oil & Gas Integrated", sector: "Energy", country: "US",
    currency: "USD", exchange_short_name: "NYSE", ipo_date: "1921-06-24", image: "https://financialmodelingprep.com/image-stock/CVX.png", years_of_dividend_growth: 34 },
  { symbol: "DOV", name: "Dover Corporation", exchange: "New York Stock Exchange", industry: "Specialty Industrial Machinery", sector: "Industrials",
    country: "US", currency: "USD", exchange_short_name: "NYSE", ipo_date: "1956-12-03", image: "https://financialmodelingprep.com/image-stock/DOV.png", years_of_dividend_growth: 65 },
  { symbol: "ECL", name: "Ecolab Inc.", exchange: "New York Stock Exchange", industry: "Specialty Chemicals", sector: "Basic Materials", country: "US",
    currency: "USD", exchange_short_name: "NYSE", ipo_date: "1957-01-01", image: "https://financialmodelingprep.com/image-stock/ECL.png", years_of_dividend_growth: 29 },
  { symbol: "ED", name: "Consolidated Edison, Inc.", exchange: "New York Stock Exchange", industry: "Utilities—Regulated Electric", sector: "Utilities",
    country: "US", currency: "USD", exchange_short_name: "NYSE", ipo_date: "1948-06-21", image: "https://financialmodelingprep.com/image-stock/ED.png", years_of_dividend_growth: 47 },
  { symbol: "EMR", name: "Emerson Electric Co.", exchange: "New York Stock Exchange", industry: "Specialty Industrial Machinery", sector: "Industrials",
    country: "US", currency: "USD", exchange_short_name: "NYSE", ipo_date: "1944-09-05", image: "https://financialmodelingprep.com/image-stock/EMR.png", years_of_dividend_growth: 59 },
  { symbol: "ESS", name: "Essex Property Trust, Inc.", exchange: "New York Stock Exchange", industry: "REIT—Residential", sector: "Real Estate", country: "US",
    currency: "USD", exchange_short_name: "NYSE", ipo_date: "1994-06-07", image: "https://financialmodelingprep.com/image-stock/ESS.png", years_of_dividend_growth: 27 },
  { symbol: "EXPD", name: "Expeditors International of Washington, Inc.", exchange: "Nasdaq Global Select", industry: "Integrated Freight & Logistics",
    sector: "Industrials", country: "US", currency: "USD", exchange_short_name: "NASDAQ", ipo_date: "2005-06-06", image: "https://financialmodelingprep.com/image-stock/EXPD.png", years_of_dividend_growth: 27 },
  { symbol: "FRT", name: "Federal Realty Investment Trust", exchange: "New York Stock Exchange", industry: "REIT—Retail", sector: "Real Estate", country: "US",
    currency: "USD", exchange_short_name: "NYSE", ipo_date: "1984-12-17", image: "https://financialmodelingprep.com/image-stock/FRT.png", years_of_dividend_growth: 49 },
  { symbol: "GD", name: "General Dynamics Corporation", exchange: "New York Stock Exchange", industry: "Aerospace & Defense", sector: "Industrials",
    country: "US", currency: "USD", exchange_short_name: "NYSE", ipo_date: "1952-04-25", image: "https://financialmodelingprep.com/image-stock/GD.png", years_of_dividend_growth: 30 },
  { symbol: "GPC", name: "Genuine Parts Company", exchange: "New York Stock Exchange", industry: "Specialty Retail", sector: "Consumer Cyclical",
    country: "US", currency: "USD", exchange_short_name: "NYSE", ipo_date: "1986-08-20", image: "https://financialmodelingprep.com/image-stock/GPC.png", years_of_dividend_growth: 65 },
  { symbol: "GWW", name: "W.W. Grainger, Inc.", exchange: "New York Stock Exchange", industry: "Industrial Distribution", sector: "Industrials", country: "US",
    currency: "USD", exchange_short_name: "NYSE", ipo_date: "1975-07-29", image: "https://financialmodelingprep.com/image-stock/GWW.png", years_of_dividend_growth: 50 },
  { symbol: "HRL", name: "Hormel Foods Corporation", exchange: "New York Stock Exchange", industry: "Packaged Foods", sector: "Consumer Defensive",
    country: "US", currency: "USD", exchange_short_name: "NYSE", ipo_date: "1990-01-16", image: "https://financialmodelingprep.com/image-stock/HRL.png", years_of_dividend_growth: 55 },
  { symbol: "IBM", name: "International Business Machines Corporation", exchange: "New York Stock Exchange", industry: "Information Technology Services",
    sector: "Technology", country: "US", currency: "USD", exchange_short_name: "NYSE", ipo_date: "1915-11-11", image: "https://financialmodelingprep.com/image-stock/IBM.png", years_of_dividend_growth: 25 },
  { symbol: "ITW", name: "Illinois Tool Works Inc.", exchange: "New York Stock Exchange", industry: "Specialty Industrial Machinery", sector: "Industrials",
    country: "US", currency: "USD", exchange_short_name: "NYSE", ipo_date: "1973-03-13", image: "https://financialmodelingprep.com/image-stock/ITW.png", years_of_dividend_growth: 50 },
  { symbol: "JNJ", name: "Johnson & Johnson", exchange: "New York Stock Exchange", industry: "Drug Manufacturers—General", sector: "Healthcare", country: "US",
    currency: "USD", exchange_short_name: "NYSE", ipo_date: "1944-09-25", image: "https://financialmodelingprep.com/image-stock/JNJ.png", years_of_dividend_growth: 59 },
  { symbol: "KMB", name: "Kimberly-Clark Corporation", exchange: "New York Stock Exchange", industry: "Household & Personal Products",
    sector: "Consumer Defensive", country: "US", currency: "USD", exchange_short_name: "NYSE", ipo_date: "1929-05-09", image: "https://financialmodelingprep.com/image-stock/KMB.png", years_of_dividend_growth: 48 },
  { symbol: "KO", name: "The Coca-Cola Company", exchange: "New York Stock Exchange", industry: "Beverages—Non-Alcoholic", sector: "Consumer Defensive",
    country: "US", currency: "USD", exchange_short_name: "NYSE", ipo_date: "1919-09-05", image: "https://financialmodelingprep.com/image-stock/KO.png", years_of_dividend_growth: 59 },
  { symbol: "LEG", name: "Leggett & Platt, Incorporated", exchange: "New York Stock Exchange", industry: "Furnishings, Fixtures & Appliances",
    sector: "Consumer Cyclical", country: "US", currency: "USD", exchange_short_name: "NYSE", ipo_date: "1979-06-25", image: "https://financialmodelingprep.com/image-stock/LEG.png", years_of_dividend_growth: 50 },
  { symbol: "LIN", name: "Linde plc", exchange: "New York Stock Exchange", industry: "Specialty Chemicals", sector: "Basic Materials", country: "GB",
    currency: "USD", exchange_short_name: "NYSE", ipo_date: "2018-10-29", image: "https://financialmodelingprep.com/image-stock/LIN.png", years_of_dividend_growth: 28 },
  { symbol: "LOW", name: "Lowe's Companies, Inc.", exchange: "New York Stock Exchange", industry: "Home Improvement Retail", sector: "Consumer Cyclical",
    country: "US", currency: "USD", exchange_short_name: "NYSE", ipo_date: "1979-12-19", image: "https://financialmodelingprep.com/image-stock/LOW.png", years_of_dividend_growth: 47 },
  { symbol: "MCD", name: "McDonald's Corporation", exchange: "New York Stock Exchange", industry: "Restaurants", sector: "Consumer Cyclical", country: "US",
    currency: "USD", exchange_short_name: "NYSE", ipo_date: "1966-07-05", image: "https://financialmodelingprep.com/image-stock/MCD.png", years_of_dividend_growth: 44 },
  { symbol: "MDT", name: "Medtronic plc", exchange: "New York Stock Exchange", industry: "Medical Devices", sector: "Healthcare", country: "IE",
    currency: "USD", exchange_short_name: "NYSE", ipo_date: "1980-03-17", image: "https://financialmodelingprep.com/image-stock/MDT.png", years_of_dividend_growth: 43 },
  { symbol: "MKC", name: "McCormick & Company, Incorporated", exchange: "New York Stock Exchange", industry: "Packaged Foods", sector: "Consumer Defensive",
    country: "US", currency: "USD", exchange_short_name: "NYSE", ipo_date: "1999-05-25", image: "https://financialmodelingprep.com/image-stock/MKC.png", years_of_dividend_growth: 35 },
  { symbol: "MMM", name: "3M Company", exchange: "New York Stock Exchange", industry: "Specialty Industrial Machinery", sector: "Industrials", country: "US",
    currency: "USD", exchange_short_name: "NYSE", ipo_date: "1946-01-14", image: "https://financialmodelingprep.com/image-stock/MMM.png", years_of_dividend_growth: 63 },
  { symbol: "NEE", name: "NextEra Energy, Inc.", exchange: "New York Stock Exchange", industry: "Utilities—Regulated Electric", sector: "Utilities",
    country: "US", currency: "USD", exchange_short_name: "NYSE", ipo_date: "1950-02-15", image: "https://financialmodelingprep.com/image-stock/NEE.png", years_of_dividend_growth: 25 },
  { symbol: "NUE", name: "Nucor Corporation", exchange: "New York Stock Exchange", industry: "Steel", sector: "Basic Materials", country: "US",
    currency: "USD", exchange_short_name: "NYSE", ipo_date: "1972-07-12", image: "https://financialmodelingprep.com/image-stock/NUE.png", years_of_dividend_growth: 48 },
  { symbol: "O", name: "Realty Income Corporation", exchange: "New York Stock Exchange", industry: "REIT—Retail", sector: "Real Estate", country: "US",
    currency: "USD", exchange_short_name: "NYSE", ipo_date: "2012-02-10", image: "https://financialmodelingprep.com/image-stock/O.png", years_of_dividend_growth: 26 },
  { symbol: "PBCT", name: "People's United Financial, Inc.", exchange: "Nasdaq Global Select", industry: "Banks—Regional", sector: "Financial Services",
    country: "US", currency: "USD", exchange_short_name: "NASDAQ", ipo_date: "1988-01-07", image: "https://financialmodelingprep.com/image-stock/PBCT.png", years_of_dividend_growth: 28 },
  { symbol: "PEP", name: "PepsiCo, Inc.", exchange: "Nasdaq Global Select", industry: "Beverages—Non-Alcoholic", sector: "Consumer Defensive", country: "US",
    currency: "USD", exchange_short_name: "NASDAQ", ipo_date: "1919-12-18", image: "https://financialmodelingprep.com/image-stock/PEP.png", years_of_dividend_growth: 48 },
  { symbol: "PG", name: "The Procter & Gamble Company", exchange: "New York Stock Exchange", industry: "Household & Personal Products",
    sector: "Consumer Defensive", country: "US", currency: "USD", exchange_short_name: "NYSE", ipo_date: "1950-03-22", image: "https://financialmodelingprep.com/image-stock/PG.png", years_of_dividend_growth: 65 },
  { symbol: "PNR", name: "Pentair plc", exchange: "New York Stock Exchange", industry: "Specialty Industrial Machinery", sector: "Industrials", country: "GB",
    currency: "USD", exchange_short_name: "NYSE", ipo_date: "2012-09-17", image: "https://financialmodelingprep.com/image-stock/PNR.png", years_of_dividend_growth: 44 },
  { symbol: "PPG", name: "PPG Industries, Inc.", exchange: "New York Stock Exchange", industry: "Specialty Chemicals", sector: "Basic Materials",
    country: "US", currency: "USD", exchange_short_name: "NYSE", ipo_date: "1945-12-17", image: "https://financialmodelingprep.com/image-stock/PPG.png", years_of_dividend_growth: 49 },
  { symbol: "ROP", name: "Roper Technologies, Inc.", exchange: "New York Stock Exchange", industry: "Specialty Industrial Machinery", sector: "Industrials",
    country: "US", currency: "USD", exchange_short_name: "NYSE", ipo_date: "1996-11-01", image: "https://financialmodelingprep.com/image-stock/ROP.png", years_of_dividend_growth: 28 },
  { symbol: "SHW", name: "The Sherwin-Williams Company", exchange: "New York Stock Exchange", industry: "Specialty Chemicals", sector: "Basic Materials",
    country: "US", currency: "USD", exchange_short_name: "NYSE", ipo_date: "1964-02-11", image: "https://financialmodelingprep.com/image-stock/SHW.png", years_of_dividend_growth: 42 },
  { symbol: "SPGI", name: "S&P Global Inc.", exchange: "New York Stock Exchange", industry: "Financial Data & Stock Exchanges", sector: "Financial Services",
    country: "US", currency: "USD", exchange_short_name: "NYSE", ipo_date: "1929-02-14", image: "https://financialmodelingprep.com/image-stock/SPGI.png", years_of_dividend_growth: 48 },
  { symbol: "SWK", name: "Stanley Black & Decker, Inc.", exchange: "New York Stock Exchange", industry: "Tools & Accessories", sector: "Industrials",
    country: "US", currency: "USD", exchange_short_name: "NYSE", ipo_date: "1966-06-15", image: "https://financialmodelingprep.com/image-stock/SWK.png", years_of_dividend_growth: 53 },
  { symbol: "SYY", name: "Sysco Corporation", exchange: "New York Stock Exchange", industry: "Food Distribution", sector: "Consumer Defensive", country: "US",
    currency: "USD", exchange_short_name: "NYSE", ipo_date: "1981-01-20", image: "https://financialmodelingprep.com/image-stock/SYY.png", years_of_dividend_growth: 41 },
  { symbol: "T", name: "AT&T Inc.", exchange: "New York Stock Exchange", industry: "Telecom Services", sector: "Communication Services", country: "US",
    currency: "USD", exchange_short_name: "NYSE", ipo_date: "1983-11-21", image: "https://financialmodelingprep.com/image-stock/T.png", years_of_dividend_growth: 36 },
  { symbol: "TGT", name: "Target Corporation", exchange: "New York Stock Exchange", industry: "Discount Stores", sector: "Consumer Defensive", country: "US",
    currency: "USD", exchange_short_name: "NYSE", ipo_date: "1969-09-08", image: "https://financialmodelingprep.com/image-stock/TGT.png", years_of_dividend_growth: 49 },
  { symbol: "TROW", name: "T. Rowe Price Group, Inc.", exchange: "Nasdaq Global Select", industry: "Asset Management", sector: "Financial Services",
    country: "US", currency: "USD", exchange_short_name: "NASDAQ", ipo_date: "1986-01-04", image: "https://financialmodelingprep.com/image-stock/TROW.png", years_of_dividend_growth: 35 },
  { symbol: "VFC", name: "V.F. Corporation", exchange: "New York Stock Exchange", industry: "Apparel Manufacturing", sector: "Consumer Cyclical",
    country: "US", currency: "USD", exchange_short_name: "NYSE", ipo_date: "1966-07-25", image: "https://financialmodelingprep.com/image-stock/VFC.png", years_of_dividend_growth: 49 },
  { symbol: "WBA", name: "Walgreens Boots Alliance, Inc.", exchange: "Nasdaq Global Select", industry: "Pharmaceutical Retailers", sector: "Healthcare",
    country: "US", currency: "USD", exchange_short_name: "NASDAQ", ipo_date: "2014-12-31", image: "https://financialmodelingprep.com/image-stock/WBA.png", years_of_dividend_growth: 45 },
  { symbol: "WMT", name: "Walmart Inc.", exchange: "New York Stock Exchange", industry: "Discount Stores", sector: "Consumer Defensive", country: "US",
    currency: "USD", exchange_short_name: "NYSE", ipo_date: "1972-08-25", image: "https://financialmodelingprep.com/image-stock/WMT.png", years_of_dividend_growth: 48 },
  { symbol: "WST", name: "West Pharmaceutical Services, Inc.", exchange: "New York Stock Exchange", industry: "Medical Instruments & Supplies",
    sector: "Healthcare", country: "US", currency: "USD", exchange_short_name: "NYSE", ipo_date: "1923-07-27", image: "https://financialmodelingprep.com/image-stock/WST.png", years_of_dividend_growth: 28 },
  { symbol: "XOM", name: "Exxon Mobil Corporation", exchange: "New York Stock Exchange", industry: "Oil & Gas Integrated", sector: "Energy", country: "US",
    currency: "USD", exchange_short_name: "NYSE", ipo_date: "1980-03-17", image: "https://financialmodelingprep.com/image-stock/XOM.png", years_of_dividend_growth: 37 },
]
