name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: yoshikouki/dividend-portal
    services:
      db:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - name: Cache bundle
        uses: actions/cache@v2
        with:
          path: |
            /app/vendor/bundle
          key: ${{ runner.os }}-${{ hashFiles('Gemfile.lock') }}
      - name: Setup
        run: |
          bundle config path /app/vendor/bundle
          bin/setup
      - name: Linter
        run: make lint
      - name: Test
        run: make test
        env:
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
