name: CI
on: [push]

jobs:
  build:
    services:
      db:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    container: yoshikouki/dividend-portal
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        run: bin/setup
      - name: Linter
        run: make lint
      - name: Test
        run: make test
